### PR TITLE
Change to global link refs

### PR DESCRIPTION
**Pull request by krealyt**
Changed the documentation links to global targets/references where not done yet. Goal: No dead links when changing the page structure of the documentation.

### CODE REVIEW

**Comment by a-w50** [comment]
Good enhancement :+1: 
Maybe we should specify a default format for global refs - I guess using spaces might be fragile?

**Comment by krealyt** [comment]
Found some examples with whitespace in the documentation here: https://docs.readthedocs.io/en/stable/guides/cross-referencing-with-sphinx.html#explicit-targets

But digging deeper, I found more evidence that your point is valid. So, will change to a format with dashes like

"maintopic-subtopic"

What do you think, @a-w50 ?

**Comment by a-w50** [comment]
> Found some examples with whitespace in the documentation here: https://docs.readthedocs.io/en/stable/guides/cross-referencing-with-sphinx.html#explicit-targets
> 
> But digging deeper, I found more evidence that your point is valid. So, will change to a format with dashes like
> 
> "maintopic-subtopic"

Right, of course it is possible.  But thinking about automatic line breaking, this might lead to problems.  I would prefer an underscore, so `maintopic_subtopic`, but thats up to you.

**Comment by krealyt** [comment]
@a-w50 I used your suggestion and changed the nomenclature. Additionally cleared the "Line too long" warnings in the paragraphs around the changes.

Tested in documentation docker container.

**Pull request merged**
