### PR TITLE
Update doc_tutorial_new_modules.rst

### PR DESCRIPTION
**Pull request by pionix-juraed**
Adding text and diagrams created by @LAD101work

### CODE REVIEW

**Review by LAD101work — CHANGES_REQUESTED** [review]
Please have a look into my comments and after that I will re-review. Thanks!

**Comment by pionix-juraed** [comment]
fixed

**Comment by pionix-juraed** [comment]
tidied up some old stuff..

**Review by LAD101work — APPROVED** [review]
Very good! Looks shiny now!

**Pull request merged**
